// flow-typed signature: f4fbcfb36151328fbae49af186d07e2e
// flow-typed version: <<STUB>>/bn.js_v=2.0.4/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bn.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bn.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bn.js/lib/bn' {
  declare module.exports: any;
}

declare module 'bn.js/test/arithmetic-test' {
  declare module.exports: any;
}

declare module 'bn.js/test/binary-test' {
  declare module.exports: any;
}

declare module 'bn.js/test/constructor-test' {
  declare module.exports: any;
}

declare module 'bn.js/test/fixtures' {
  declare module.exports: any;
}

declare module 'bn.js/test/pummel/dh-group-test' {
  declare module.exports: any;
}

declare module 'bn.js/test/red-test' {
  declare module.exports: any;
}

declare module 'bn.js/test/utils-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bn.js/lib/bn.js' {
  declare module.exports: $Exports<'bn.js/lib/bn'>;
}
declare module 'bn.js/test/arithmetic-test.js' {
  declare module.exports: $Exports<'bn.js/test/arithmetic-test'>;
}
declare module 'bn.js/test/binary-test.js' {
  declare module.exports: $Exports<'bn.js/test/binary-test'>;
}
declare module 'bn.js/test/constructor-test.js' {
  declare module.exports: $Exports<'bn.js/test/constructor-test'>;
}
declare module 'bn.js/test/fixtures.js' {
  declare module.exports: $Exports<'bn.js/test/fixtures'>;
}
declare module 'bn.js/test/pummel/dh-group-test.js' {
  declare module.exports: $Exports<'bn.js/test/pummel/dh-group-test'>;
}
declare module 'bn.js/test/red-test.js' {
  declare module.exports: $Exports<'bn.js/test/red-test'>;
}
declare module 'bn.js/test/utils-test.js' {
  declare module.exports: $Exports<'bn.js/test/utils-test'>;
}
