// flow-typed signature: 9196b46970529d3bae21f2bfb9d11b98
// flow-typed version: <<STUB>>/elliptic_v=3.0.3/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'elliptic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'elliptic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'elliptic/lib/elliptic' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/curve/base' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/curve/edwards' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/curve/index' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/curve/mont' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/curve/short' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/curves' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/der' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/ec/index' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/ec/key' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/ec/signature' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/hmac-drbg' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/precomputed/secp256k1' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/utils' {
  declare module.exports: any;
}

declare module 'elliptic/test/api-test' {
  declare module.exports: any;
}

declare module 'elliptic/test/curve-test' {
  declare module.exports: any;
}

declare module 'elliptic/test/ecdh-test' {
  declare module.exports: any;
}

declare module 'elliptic/test/ecdsa-test' {
  declare module.exports: any;
}

declare module 'elliptic/test/hmac-drbg-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'elliptic/lib/elliptic.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic'>;
}
declare module 'elliptic/lib/elliptic/curve/base.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/curve/base'>;
}
declare module 'elliptic/lib/elliptic/curve/edwards.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/curve/edwards'>;
}
declare module 'elliptic/lib/elliptic/curve/index.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/curve/index'>;
}
declare module 'elliptic/lib/elliptic/curve/mont.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/curve/mont'>;
}
declare module 'elliptic/lib/elliptic/curve/short.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/curve/short'>;
}
declare module 'elliptic/lib/elliptic/curves.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/curves'>;
}
declare module 'elliptic/lib/elliptic/der.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/der'>;
}
declare module 'elliptic/lib/elliptic/ec/index.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/ec/index'>;
}
declare module 'elliptic/lib/elliptic/ec/key.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/ec/key'>;
}
declare module 'elliptic/lib/elliptic/ec/signature.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/ec/signature'>;
}
declare module 'elliptic/lib/elliptic/hmac-drbg.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/hmac-drbg'>;
}
declare module 'elliptic/lib/elliptic/precomputed/secp256k1.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/precomputed/secp256k1'>;
}
declare module 'elliptic/lib/elliptic/utils.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/utils'>;
}
declare module 'elliptic/test/api-test.js' {
  declare module.exports: $Exports<'elliptic/test/api-test'>;
}
declare module 'elliptic/test/curve-test.js' {
  declare module.exports: $Exports<'elliptic/test/curve-test'>;
}
declare module 'elliptic/test/ecdh-test.js' {
  declare module.exports: $Exports<'elliptic/test/ecdh-test'>;
}
declare module 'elliptic/test/ecdsa-test.js' {
  declare module.exports: $Exports<'elliptic/test/ecdsa-test'>;
}
declare module 'elliptic/test/hmac-drbg-test.js' {
  declare module.exports: $Exports<'elliptic/test/hmac-drbg-test'>;
}
